- .github/workflows/ci.yml
- docs/examples/go-md2man-1.yml
- docs/examples/go-md2man-2.yml
- docs/intro.md
- docs/spec.schema.json
- docs/testing.md
- frontend/gateway.go
- frontend/rpm/handle_sources.go
- load.go
- load_test.go
- source.go
- spec.go
- test/fixtures/cmd-src-ref.yml
- test/fixtures/frontend.yml
- test/fixtures/git-patch.yml
- test/fixtures/http-src.yml
- test/fixtures/kubernetes-patch.yml
- test/fixtures/local-context.yml
- test/fixtures/moby-runc.yml
- test/fixtures/nested.yml
- test/fixtures/test-framework.yml
Replaces PR #57 , see #57 for all comments which have been addressed by now.
There was a snafu with the Azure/dalec repo going public, so I had to re-fork.
> feat: Remove magic strings from Source type

- load.go
This was causing `image:` sources to panic when there was no `cmd:` field specified in the spec.
> fix: potential nil pointer reference

- docs/spec.schema.json
- files.go
- frontend/debug/handle_sources.go
- frontend/rpm/handle_sources.go
- frontend/rpm/template.go
- load.go
- load_test.go
- source.go
- source_test.go
- spec.go
- test/handlers_test.go
- test/helpers_test.go
- test/source_test.go
- test/testenv/buildx.go
- test/var_passthrough_test.go
This allows you to specify files or trees inline in yaml spec.
Example:
```yaml
sources:
someFile:
inline:
file:
contents: "hello!"
someDir:
inline:
dir:
files:
foo:
contents: "I am foo!"
```
You can also set permissions and ownership.
> Add support for inline sources

- helpers.go
Using weak progress groups seems to hide all the output from the progress group.
Need to understand more of how to use weak groups, for now use non-weak ones for everything so we can get helpful output.
> Revert use of "weak" progress groups.

- load.go
- load_test.go
- test/fixtures/unmarshall/source-inline.yml
This PR adds strict option for yaml unmarshal, any unknow field or typo `field` in a dalec spec will result in error
This should solve Issue #81 
example output when trying to build example with unknow field.
```
go-md2man-2.yml:1
--------------------
1 | >>> # syntax=local/dalec/frontend:latest
2 |     name: go-md2man
3 |     version: 2.0.3
--------------------
ERROR: failed to solve: error loading spec: error unmarshalling spec: [9:1] unknown field "fake-field"
6 | license: MIT
7 | description: A tool to convert markdown into man pages (roff).
8 | website: https://github.com/cpuguy83/go-md2man
>  9 | fake-field: test
^
10 | sources:
11 |   src:
12 |     git:
```
> Add strict yaml unmarshal option

- .github/workflows/frontend-image.yml
- .github/workflows/release.yml
When the repo is tagged (and that tag looks like a version number), the release workflow is triggered and will start a frontend build with the git tag (minus the leading `v`) as image tag.
Example (after a few tests) is here: https://github.com/cpuguy83/dalec-test-fork/actions/runs/8012326758
Which produced https://github.com/cpuguy83/dalec-test-fork/pkgs/container/dalec-test-fork%2Ffrontend/182474475?tag=0.1.5
> Add release workflow

- .github/dependabot.yml
Remove some dependabot jobs
1. We don't have the image at frontend/mariner2 anymore, so that is not needed at all
2. For go deps, ignore major/minor version updates which can all be
tricky for transative (or shared) upstream dependencies.
> Remove some dependabot jobs

- docs/intro.md
- load.go
- load_test.go
This allows clients to store extra data in the spec without having to loosen up unmarshalling validations.
No "x-" field is explicitly added to the spec because frontends should not be interpreting this field.
Instead the fields are stripped from the input before unmarshalling to `Spec`.
> Allow fields starting with `x-` in the spec

- frontend/rpm/handle_rpm.go
- test/main_test.go
- test/mariner2_test.go
Generally the build phase should be completely isolated, this makes sure that consumers of the srpm can reliably rebuild packages.
This may be somewhat controversial.
If we need to we can add a toggle for this later.
Mainly I don't want to release anything now that allows internet access only to take it away later (which will be much harder after anyone starts adopting dalec).
> Disable network access during rpmbuild

- docs/spec.schema.json
- frontend/mariner2/handle_rpm.go
- frontend/rpm/handle_buildroot.go
- frontend/rpm/handle_rpm.go
- frontend/rpm/handle_spec.go
- spec.go
These fields are required to build an rpm.
When the fields are not there rpmbuild gives an error about the fields,
but those field names are different so its confusing to the user.
This checks those fields early so we can give a better error message.
> Validate rpm fields

- .github/workflows/frontend-image.yml
- .github/workflows/release.yml
- Modify the fronted job to support a comma separated tag list
- Modify release workflow to send multiple tags to the build job:
- `latest`
- `<major>.<minor>`
- `<major>.<minor>.<patch>`
> Release multiple tags

- docs/spec.schema.json
- frontend/mariner2/handle_container.go
- image.go
- spec.go
This allows the spec to override the user in the base image.
Closes #140
> Add user in image config

- load.go
Adds initial support for `SOURCE_DATE_EPOCH`, technically this variable was already able to be injected in Dalec specs as one of the requirements to add this is to explicit require the `args/envs`.  It seems like `SOURCE_DATE_EPOCH` env var is auto injected by docker/buildx so no need to explicit `--build-arg`. The difference I could notice is that now with change applied the build will not fail as unknow arg for `SOURCE_DATE_EPOCH` var but it still requires the spec to set this variable to be used.
```yml
args:
SOURCE_DATE_EPOCH: # [Required] Needs to explicit call for variable to be usable within spec
name: go-md2man
version: 2.0.3
packager: Dalec Example
...
sources:
...
build:
env:
SOURCE_DATE_EPOCH: ${SOURCE_DATE_EPOCH} # [Required] Needs to …
```
> add initial support for SOURCE_DATE_EPOCH

- source.go
- source_test.go
- test/source_test.go
The old behavior was odd in this case where it could mount the file into a subdirectory of the path we requested (not desirable) and it was named after the parent source.
E.g. if you have an image source "foo" and you specify a file-based source at mount point '/some_file', it would mount this file as "/some_file/foo".
Related to the comment in this gist: https://gist.github.com/cpuguy83/c570f3ea97af215af63264061cac94af#file-spec-yaml-L114
> Fix mounting file into image source

- frontend/mux.go
- frontend/mux_test.go
Before this change, when the BuildMux's prefix route matching is used it would itterate the map of routes and use the first prefix match it finds.
Map ordering is non-deterministic so there was only a random chance that it would pick the closest match.
When itterating the map it now keeps a list of all possible candidates, then sorts those to select the best possible prefix match. The best candidate is the one with the longest set of matching characters.
As an example if we have two routes:
- `a`
- `a/other`
And a requested route of `a/other/1`
It would have a random chance of hitting `a/other` vs `a`, even though we *always* want `a/other` in this case.
> Fix subrouting when parent path has match

- docs/spec.schema.json
- load.go
- source.go
- source_test.go
- spec.go
- test/source_test.go
This is needed to ensure the integrity of http sources.
Closes #64 (or at least to the best we can possibly handle in dalec).
> Add support for validating HTTP by digest

- docs/examples/go-md2man-1.yml
- docs/examples/go-md2man-2.yml
- docs/spec.schema.json
- frontend/debug/handle_gomod.go
- frontend/debug/handler.go
- frontend/mariner2/handle_rpm.go
- frontend/mariner2/handler.go
- frontend/rpm/handle_buildroot.go
- frontend/rpm/handle_sources.go
- frontend/rpm/handler.go
- frontend/rpm/template.go
- frontend/rpm/template_test.go
- frontend/windows/handle_zip.go
- generator_gomod.go
- load.go
- load_test.go
- source.go
- spec.go
- test/fixtures/frontend.yml
- test/helpers_test.go
- test/source_test.go
- website/docs/intro.md
This adds a new `Generate` field on `Source` which is a list of
generator configs.
Today the only type of generator we support is for go modules but we'll
likely need to add support for other things, e.g. Rust cargo deps.
Multiple geneator configs are allowed in the case of a source with
multiple go modules defined in it.
Closes #180
> Add support for generating go module deps

- frontend/windows/handle_zip.go
- helpers.go
- test/mariner2_test.go
- test/source_test.go
- test/windows_test.go
Some minor fixes + fixes an issue with gomods on the windows target.
Found the gomods issue while rebasing #87.
Extracted a few of the commits out of there into this PR to address.
Some changes in this PR just made it easier to shift to a new PR.
> Fix some gomods issues

- docs/spec.schema.json
- frontend/mariner2/handle_container.go
- frontend/mariner2/handle_rpm.go
- frontend/test_runner.go
- helpers.go
- spec.go
- test/fixtures/moby-runc.yml
We were never installing test dependencies before. Installing test deps requires some careful handling to not modify containers too much and as such should be used only when necessary.
Test dependencies do not alter the output container, only the container under test, and only when there are commands that need to be run in the container since the built-in test handlers do not require any extra tooling.
> Actually use test depdenencies

- frontend/mariner2/handle_container.go
- frontend/mariner2/handle_depsonly.go
Before this we were using the distroless image's rootfs as the base for the output container.
With this change an empty rootfs is used unless the spec has an image specified.
Closes #51
> mariner2: Use empty rootfs for default container

- README.md
- SUPPORT.md
Updating result of running `BUILDX_EXPERIMENTAL=1 docker build --print=targets -f test/fixtures/moby-runc.yml .`
Is it possible to maybe create a target maybe in the `docker-bake.hcl` or something easier to remember for this command?
> docs: update available targets on README.md

- docs/spec.schema.json
- frontend/rpm/template.go
- spec.go
- test/mariner2_test.go
This PR adds the ability to specify directories that should be created for %{_sharedstatedir} and  %{_sysconfdir}
This will ensure they are created during the install phase and that they show up in the files section of the resulting RPM spec.
In the spec, this would look like:
```
artifacts:
createDirectories:
config:
kubernetes: 
mode: 0755
kubernetes/manifests: {}
state:
kubelet: {}
```
This would result in:
```
%install
mkdir -m 755 -p "%{buildroot}/%{_sysconfdir}/kubernetes"
mkdir -p "%{buildroot}/%{_sysconfdir}/kubernetes/manifests"
mkdir -p "%{buildroot}/%{_sharedstatedir}/kubelet"
%files
%dir %{_sysconfdir}/kubernetes
%dir %{_sysconfdir}/kubernetes/manifests
%dir %{_sharedstatedir}/kubelet
```
**Which issue(s) this PR fixes** *(optional, …
> Add ability to specify shared state and config directories

- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_rpm.go
- frontend/request.go
- frontend/windows/handle_container.go
- frontend/windows/handle_zip.go
I don't have a good test case for this right now.
I'll open an issue because ideally we can ensure that this doesn't regress in the future.
> fix: Ensure container targets use signed artifact

- website/docs/signing.md
Updating docs in reference to singing,
This is a bit contradicting to Original PR in [dalec-build-defs](https://github.com/Azure/dalec-build-defs/pull/66#issue-2275877981), were shown example uses `mariner2/container` target and leverages signing!
Not sure what is the correct, if the example is wrong or we are missing the the signing frontend call during `mariner2/container` call.
> docs: update signing details

- docs/spec.schema.json
- frontend/rpm/template.go
- spec.go
- test/azlinux_test.go
This PR adds the ability to add files to the package and have them represented by the `%doc` directive or the %license directive within the %files list.
There isn't a corresponding install entry, because RPM handles this already:
> When the package is installed, RPM creates a directory in the documentation directory named the same as the package and copies the file there
The same happens with license files. 
I thought that a slice of strings made more sense than using ArtifactConfig here, since we don't really need to provide any other real options. It seems like you can specify a full path with the %doc directive (%license as well), but I think we can go with this for now? It feels cleaner/more organized. 
**Which issue(s) this PR fixes** …
> Add handling for docs files and license files

- frontend/rpm/template.go
- frontend/rpm/template_test.go
This PR corrects a few unexpected results when generating a package 
Fixes #265 
55ff43e7480aadaafb09a3da77e49c47a97a2fae refactors a bit to create a new function that will use filepath.Base as default and replace it with cfg.Name if provided
507e531af5ff3c547b6c88e7643111cbbb81e634 changes how license and doc files are handled, because currently they need to be at the root of the buildroot unless a subpath was specified
> Fix filepath handling for a few types

- docs/spec.schema.json
- frontend/rpm/template.go
- frontend/rpm/template_test.go
- spec.go
- test/azlinux_test.go
This PR adds support for specifying systemd dropin config files. As part of this, I refactored the existing systemd block to nest units and dropins under a `systemd` field. 
This PR adds tests both to both the unit tests for template.go and for the az_linux tests. 
Fixes #271
> Support SystemD Drop Ins

- test/fs_test.go
calling fs.WalkDir() on `/` it doesn't produce expected behavior in comparation to `.` which works fine. Maybe this should be its own issue. But this issue was not raised for two things we first check if path is `/` and return instead of check for error first. And second, we didn't have a comparation of the actual # calls against expected calls.
> fix false run on fs.walkdir test

- frontend/windows/handle_container.go
- frontend/windows/handle_zip.go
- go.mod
- go.sum
- test/fixtures/phony.go
- test/fixtures/signer.go
- test/testenv/buildx.go
- test/windows_test.go
1. Removes custom buildx config inpsection for new `buildx dial-stdio` subcommand for creating a buildkit client. This not only allows *any* buildx instance to be used, in particular it unblocks docker desktop.
2. Sets test fixtures to explicitly set the platform to the worker's platform. This is needed because the LLB is generated on the client and was assuming the client's platform (e.g. darwin/arm64 on mac).
3. Marks windows tests to use explictlty set amd64 as the target platform since windows/arm64 is not supported. This allows the test suite to run against an arm64 worker (e.g. docker for mac).
> tests: Allow test suite to run on mac

- .github/workflows/ci.yml
- cmd/test2json2gha/main.go
Add a test2json formatter for better output on github actions.
This will:
1. Group all test output per each individual test, which are collapsed per each test in the job console output.
2. Add indicator in test group name to highlight failed tests in the console.
3. Adds annotations for failed tests, with notices for the fail line in the file diff and also in the workflow summary.
---
Orignally started with [gotestfmt](https://github.com/gotesttools/gotestfmt) which is pretty nice, but it doesn't support outputting annotations which is really the main thing I wanted.
> ci: Add test output formatter

- test/windows_test.go
The test is using a mariner2 container to test the output of the windowscross/zip target.
The platform was incorrectly set to use windows/amd64 for the mariner2 container causing the build to fail.
> test: Fix windows test using wrong platform

- source_test.go
delete unused test function parameter
> delete unused test function parameter

- frontend/rpm/template.go
- frontend/rpm/template_test.go
When building the rpm spec we were using the wrong set of constraints for runtime dependencies.
This was likely just a bad copy/paste.
Added tests for this.
> rpm: Fix use of inccorrect field for runtime constraints

- docs/spec.schema.json
- frontend/request.go
- helpers.go
- load.go
- load_test.go
- spec.go
- test/azlinux_test.go
- test/fixtures/signer/main.go
- test/signing_test.go
- test/windows_test.go
- website/docs/signing.md
I considered extending this to allow this for any kind of frontend (and as such sticking it into the `dalec.Frontend` type), however there really shouldn't be different vars passed to target frontends. Hence why I am restricting this to just signers for now.
If we decide to later we can add this more generically, however it will be much more difficult to take it away if we decide it was a bad idea.
Related to #263
> Add support for passing build args to signers

- load.go
- load_test.go
- source.go
- source_test.go
Adds additional validations to sources to prevent hitting cryptic errors, or worse unexpected data in a specified source.
> Fix cmd mounts

- frontend/rpm/template.go
- spec.go
This PR prevents the fields `%post`, `%preun`, and `%postun` from being written to the rpm SPEC unless they are specified in the dalec spec.
This is a short-term solution to the problem specified in #298. Please see that issue for more details on the long-term solution. A short summary of the problem follows:
What is happening is that the presence of the `%post`, `%preun`, or `%postun` causes `/bin/sh` to be baked into the dependencies of the rpm. This makes sense because a shell is needed to execute the postinstall scripts, and would be needed to run pre- or post- uninstall scripts.
_without %post_:
```
$ rpm -q --requires /tmp/out/RPMS/x86_64/oras-v1.2.0-1.cm2.x86_64.rpm
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1 …
```
> fix: Don't emit rpm spec fields if empty in dalec spec

- docs/spec.schema.json
- frontend/rpm/template.go
- helpers.go
- spec.go
- test/azlinux_test.go
Deb based distros enable systemd units by default as opposed to mariner (and other rpm distros) which do not enable by default.
By making the systemd unit's enable field optional we can choose to use the default for a distro when the enable field is unset.
> Make systemd unit enable optional

- docs/spec.schema.json
- frontend/rpm/template.go
- spec.go
- test/azlinux_test.go
Users have requested the ability to put read-only architecture-independent data files under `/usr/share`.
Related #242 (does not completely resolve)
> feat: add support for datadir in rpm spec

- docs/spec.schema.json
- frontend/rpm/rpmbuild.go
- frontend/rpm/template.go
- frontend/rpm/template_test.go
- spec.go
- test/azlinux_test.go
This also cleans up some of the rpm spec template layout for easier reading.
Closes #276
> rpm: Don't emit optional fields when empty

- frontend/rpm/template.go
- frontend/rpm/template_test.go
- test/azlinux_test.go
If a different name is provided for a systemd unit artifact the unit is not being installed under that name currently. This PR fixes the bug.
Fixes #
> Fix systemd artifact install to account for artifact name

- frontend/azlinux/handle_rpm.go
- frontend/request.go
- frontend/windows/handle_zip.go
- helpers.go
- load.go
- test/azlinux_test.go
- test/helpers_test.go
- test/signing_test.go
- website/docs/signing.md
Allows the user to skip signing by adding `--build-arg DALEC_SKIP_SIGNING=1` to their `docker build` invocation. This is a partial resolution of #282. I will submit a separate PR that implements the remainder of #282.
> feat: Add known build arg to disable signing

- docker-bake.hcl
- docs/spec.schema.json
- frontend/rpm/template.go
- frontend/rpm/template_test.go
- image.go
- spec.go
- test/azlinux_test.go
- test/fixtures/frontend.yml
- test/fixtures/moby-runc.yml
- test/windows_test.go
This is another commit I've pulled out for of the jammy.
It allows constraints to apply to specific architectures+version combos which is something I realized we were missing while going through the debian control file spec.
> Use strong type for package constraints

- frontend/gateway.go
- frontend/request.go
- test/azlinux_test.go
- test/testenv/buildx.go
- test/windows_test.go
When signing is explicitly disabled this surfaces a warning message on the client.
Example:
> Send client warning when signing is disabled

- source.go
- test/source_test.go
This is just a difference in how the states are stored when there is a subpath in a directory that is the patch source (as compared to a patch file).
> Fix patching from dir with gomod generator

- website/docs/build-source.md
Example command is missing context,
and point to spec `docs/examples/go-md2man.yml`
> fix example build dalec container command

- frontend/azlinux/azlinux3.go
- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_depsonly.go
- frontend/azlinux/handle_rpm.go
- frontend/azlinux/handler.go
- frontend/azlinux/mariner2.go
- frontend/windows/handle_container.go
- frontend/windows/handle_zip.go
- frontend/windows/handler.go
- test/azlinux_test.go
- test/helpers_test.go
- test/signing_test.go
- test/testenv/builld.go
- test/windows_test.go
- website/docs/targets.md
Allow custom worker images
This allows builders to provide their own worker image via build context.
This enables builders to install their own repos, as an example, or use pre-built workers.
Adds `azlinux3/worker`, `mariner2/worker`, and `windowscross/worker/` build targets which outputs each worker image respectively.
You can take the output of these, inject whatever is needed, and feed that as an input into another build.
Note: By using the image ref as a build-context name, this brings dalec more inline with how Dockerfile works as well.
> Allow custom worker images

- frontend/azlinux/handle_rpm.go
- frontend/debug/handle_gomod.go
- frontend/debug/handle_resolve.go
- frontend/debug/handle_sources.go
- frontend/rpm/handle_buildroot.go
- frontend/rpm/handle_sources.go
- frontend/rpm/handle_spec.go
- frontend/windows/handle_zip.go
- test/windows_test.go
This fixes 2 things:
1. Always return a non-nil image config for build artifacts regardless of if they are an image [1].
2. Tests: set platform on returned llb.State [2]
This can cause some issues in buildkit libs and also yields a cryptic
error on the docker CLI for these non-container targets when the build
is not outputing tot he local dir.
One specific case right now is the dockerui client which drives all the
build targets will panic on the windowscross/zip target when using
windows as a target platform.
In the past this has also caused panics in dockerd and buildkit. These
have been fixed upstream and were considered security issues due to a
frontend being able to panic dockerd, but I don't think we should
continue doing this.
Something to consider in the future is to either replace …
> Fix test platforms

- frontend/azlinux/azlinux3.go
- frontend/azlinux/handle_container.go
- frontend/azlinux/handler.go
- frontend/azlinux/mariner2.go
- test/azlinux_test.go
This is needed for scanners and other things and is just generally good to have in the image.
Before, scanning the output of the `runc-azlinux3-container` target yields the following: (note that it can't detect the OS)
<details>
```
DOCKER_HOST=unix:///Users/cpuguy83/.docker/run/docker.sock trivy image runc:azlinux3
2024-08-01T15:59:08-07:00	INFO	[vuln] Vulnerability scanning is enabled
2024-08-01T15:59:08-07:00	INFO	[secret] Secret scanning is enabled
2024-08-01T15:59:08-07:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-08-01T15:59:08-07:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.54/docs/scanner/secret#recommendation for faster secret detection
2024-08-01T15:59:08-07:00	INFO	Detected OS	family="none" …
```
> azlinux: Make sure we install /etc/os-release

- website/docusaurus.config.ts
There is an extra /docs/ causing a 404 when clicking on the "Edit this page" button, for instance the button on https://azure.github.io/dalec/build-source points to https://github.com/Azure/dalec/blob/main/website/docs/docs/build-source.md, but the correct one is https://github.com/Azure/dalec/blob/main/website/docs/build-source.md
> docs: Fix edit URL

- frontend/azlinux/azlinux3.go
- website/docs/targets.md
... since these are available now
Fixes #
> azlinux3: use images from mcr

- website/docs/spec.md
We haven't yet documented how to opt-in to TARGET{OS, ARCH, VARIANT, PLATFORM} args in Dalec. This PR adds those docs.
Fixes #97 
> Add docs on built-in TARGET* build args

- source.go
- test/source_test.go
Before this, given an image source with multiple steps
```yaml
path: /bar
image:
ref: foobar
steps:
- command: echo foo > /foo
- command: [ -f /foo ]
```
The 2nd step would fail because the rootfs state was not being persisted between steps, only the changes to the path that is output for the source.
> fix: source: cmd: Persist rootfs state across steps

- frontend/debug/handle_sources.go
- frontend/gateway.go
- frontend/request.go
- source.go
- source_test.go
- test/source_test.go
This makes sure that if a path is specified on a context source that we we only ever fetch the content from beneath that path.
Before this change we were doing the context path filtering after the content was fetched.
This also makes so that include/exclude patterns are automatically namespaced by the source path, since it doesn't make sense to include files that are outside of the source path.
> source: context: Optimize fetch by path

- artifacts.go
- docs/spec.schema.json
- frontend/deb/debroot.go
- frontend/rpm/template.go
- go.mod
- go.sum
- test/azlinux_test.go
- test/helpers_test.go
- website/docs/artifacts.md
- website/docs/spec.md
- website/sidebars.ts
Adds support for library files and package-level symlinks.
These are required for supporting packages such as golang.
Also adds more in-depth docs for artifacts.
> Add symlink and libs artifact types

- docs/spec.schema.json
- helpers.go
- source.go
- source_test.go
- spec.go
- website/docs/sources.md
Allows the client to pass in custom git auth secrets.
Also documents the existing defaults that are used.
> Support customizing git auth

- frontend/windows/handle_container.go
- helpers.go
- test/azlinux_test.go
- test/windows_test.go
Some images need binaries and files to be in some other places than traditional packages. To enable this the `Symlinks` field was introduced.
But if one wants to create a symlink in an non existing directory the creation fails.
This PR adds an option to create the underlying directory if it does not exist.
1. ~~As far as I understood the Windows path does not need to be update because it creates the directories every time~~ Windows path doesn't create the dir, too
2. It can be argued that this shouldn't be an option and the directory creation should be …
> spec.image.postinstall.symlink: Add CreateDir option

- docs/spec.schema.json
- spec.go
This was never meant to be a required field, so mark it as omitempty so that the jsonschema validation in editors don't complain about it being missing.
> Make keepGitDir optional

- frontend/azlinux/handle_rpm.go
- frontend/jammy/handle_deb.go
- frontend/test_runner.go
This makes it so error messages from the build are not wrapped in error messages for tests.
Before this change the build is performed lazily until the point when the tests try to interact with the rootfs under test making it appear like a build failure is a test error when in reality we didn't even get to the test.
Closes #400
> Force evaluation before test execution

- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_rpm.go
- frontend/azlinux/handler.go
- frontend/jammy/handle_container.go
- frontend/jammy/handle_deb.go
- helpers.go
- test/azlinux_test.go
- test/jammy_test.go
This is a follow up PR to #366. With this PR Dalec now accepts specifying dependencies from outside package repos on Jammy targets.
Fixes #211 
> Add Custom Repo Support For Jammy

- spec.go
- test/azlinux_test.go
The file checker takes an `os.FileMode` which contains things other than just permissions.
Make the checker explictly call `mode.Perm()` to ensure it has *just* the permissions bits when checking.
This fixes an issue when checking permission on a directory.
> Fix: testrunner: Explicitly check permissions

- frontend/test_runner.go
- test/azlinux_test.go
This was simply using the wrong subpath before.
Added tests to validate that this is working correctly.
> Fix: testrunner: Use proper path for source subpath

- frontend/jammy/handle_container.go
- frontend/jammy/handle_deb.go
- test/azlinux_test.go
- test/windows_test.go
A few fixes here:
1. Minor refactor on custom repo tests so that the proper `*testing.T` is being used. This fixes a problem with the test build not producing any logs making it hard to figure out what the error is.
2. Namespace dep package names per test so that we don't have 2 parallel tests using the same package name, potentially creating a race where the package is cached and re-used in the other test.
3. Remove cached repo data for local repos (e.g., ones created in /top/repo) to fix the case where a repo can appear to become unsigned causing apt to error out.
> Fix custom repo test

- frontend/deb/template_control.go
- frontend/deb/template_control_test.go
- frontend/jammy/handle_deb.go
> jammy: handle multi version constraint on package dep

- docs/spec.schema.json
- frontend/azlinux/handle_rpm.go
- frontend/deb/pkg.go
- frontend/jammy/handle_deb.go
- frontend/rpm/rpmbuild.go
- frontend/windows/handle_zip.go
- helpers.go
- load.go
- spec.go
- test/azlinux_test.go
- test/network_test.go
- test/windows_test.go
- website/docs/spec.md
Adds a field `network_mode`. The value of this field can be any of:
- Unset
- "none" - Disable networking (default)
- "sandbox" - Networking enabled with its own network namespace
Buildkit supports `host` mode as well, but I have opted to not support that here for now.
> Add support for allowing network access during build

- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_rpm.go
- frontend/jammy/handle_deb.go
- frontend/windows/handle_zip.go
- helpers.go
- test/azlinux_test.go
- test/custom_repo_test.go
- test/helpers_test.go
- test/jammy_test.go
- test/windows_test.go
This is mostly copied from the jammy implementation since the windows target is currently using jammy as the build worker.
> windows: Add pinned deps and custom repo support

- .github/workflows/ci.yml
- frontend/deb/templates/debian_rules.tmpl
debbuild will automatically execute this `dh_dwz` target which, for some go builds, will error out like:
```
0.69 dwz: debian/msft-golang/usr/lib/msft-golang/bin/go: Found compressed .debug_abbrev section, not attempting dwz compression
40.69 dwz: debian/msft-golang/usr/lib/msft-golang/bin/gofmt: Found compressed .debug_abbrev section, not attempting dwz compression
40.69 dwz: Too few files for multifile optimization
```
This does what dh_golang does and overrides this so the target doesn't do anything.
We may want to make this opt-in in the future somehow (or scope it down to just go builds?).
Not really sure what a good approach will be here, but for now this is blocking being able to build certain packages.
> deb: Disable dh_dwz which can cause issues for go

- frontend/azlinux/azlinux3.go
- frontend/azlinux/mariner2.go
Mistakenly thought this was part of the distroless minimal package but its not.
> azlinux: include prebuilt-ca-certificates in image

- website/docs/examples/repos/msft-azl-cloud-native.yml.md
- website/docs/examples/repos/msft-ubuntu.yml.md
- website/docs/repositories.md
- website/docs/spec.md
- website/sidebars.ts
> docs: Add doc for custom repos.

- docs/spec.schema.json
- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_rpm.go
- frontend/jammy/handle_container.go
- frontend/jammy/handle_deb.go
- frontend/windows/handle_zip.go
- helpers.go
- load.go
- load_test.go
- source.go
- spec.go
- test/azlinux_test.go
- test/custom_repo_test.go
- test/jammy_test.go
- website/docs/examples/repos/msft-ubuntu.yml.md
- website/docs/repositories.md
- website/docs/sources.md
This PR adds a few fixes for the custom repos feature. 
1. Adds code to fill defaults in the extra_repos section of the spec.
3. Adds a `permissions` field to the http source. This allows us to fill in the permissions by default if they are on an http source that is nested under a key. It is important that fetched gpg keys have the proper permissions, otherwise apt cannot import them properly. Assuming that they do have proper permissions, apt can handle both `.asc` and `.gpg` keys just fine. This makes the explicit de-armor step unnecessary and means we no longer need gpg as a dependency in the jammy worker images.
4. Adds armored and de-armored key test variants to the custom repo tests to ensure everything is working properly. 
**Which issue(s) …
> Custom Repo Fixes

- frontend/azlinux/azlinux3.go
- frontend/azlinux/handler.go
- frontend/azlinux/mariner2.go
> Fix typo in target printing

- docker-bake.hcl
- frontend/build.go
- test/azlinux_test.go
Set image config created time
Before this was just using whatever created time was set on the base
image config which was incorrect.
Example using the `docker buildx bake runc-jammy-container` command:
Before:
docker image ls | grep runc
runc                                          jammy             8d1d42e074f3   25 minutes ago   228MB
After:
docker image ls | grep runc
runc                                          jammy             03c24620c8fa   5 seconds ago    228MB
**Note**: how the created time before was 25mins ago (b/c apparently the base
jammy image was recently updated, I've seen this be 2 weeks) compared to
after its 5 seconds ago.
> Set image create

- frontend/deb/distro/install.go
- helpers.go
In some cases, if `apt update` had an error, the content `apt update`
was trying to fetch will be stored in `/var/lib/apt/lists/partial`.
In Dalec, `/var/lib/apt/lists` is a persistent cache.
As a note: `apt update` does not exit non-zero here, but `apt install`
might... depending on if the package is already in the local package
cache, which can make finding this issue pretty difficult.
For certain errors this can make builds unrecoverable since there's no
real way to clean up this cache outside of blowing away the entire build
cache.
This change just clears out anything in `/var/lib/apt/lists/partial`
before calling `apt update` since it should not be needed anyway and is
potentially problematic to have.
---
The issue here is sometimes a user can provide bad input (like gpg keys with …
> apt: fix potential issue from prior build errors in cache

- frontend/mux.go
This warning was added in 9a2b35e1b14d6b7984925d0d33233226645dd82e to try and help reduce confusion if the spec contains targets and therefore we skip loading other targets.
As it turns out, its a bit overzealous if you specfy anything in the `targets` section:
8 warnings found (use docker --debug to expand):
- Skipping loading of built-in target "bullseye" since it is not in the list of targets in the spec
- Skipping loading of built-in target "mariner2" since it is not in the list of targets in the spec
- Skipping loading of built-in target "azlinux3" since it is not in the list of targets in the spec
- Skipping loading of built-in target "windowscross" since it is not in the list of targets in the spec
- Skipping loading of built-in target "bionic" since it is not in the list of …
> Remove warning message about skipping build targets

- frontend/test_runner.go
- helpers.go
- source.go
- source_test.go
- test/azlinux_test.go
- test/source_test.go
Mounts were using the destination path as the source name when generating a source, this made it so mounts would only work correctly if mounted at the root of the filesystem since source names generally should not have path separators.
Fixes #459
> Fix issue mounting files

- deps.go
- frontend/build.go
- frontend/mux.go
- helpers.go
- load.go
- load_test.go
- source.go
- spec.go
- target.go
- tests.go
Cherry-picks 8cc2df0f06e991e5078b843a80d6454ac0a15787 from #480 to avoid merge conflicts
Adds tests and fixes implementations where we weren't filling default
values and expanding args.
This was mostly a problem for anything under the `targets` section, but
also a few other fields where arg expansion is nice to have (such as in
test commands).
Also splits some types/functions off to separate files so we don't have one mega file.
Fixes #479
Fixes #467
> fix: make sure fill defualts and expand args for all types 

- .github/workflows/ci.yml
- cmd/test2json2gha/event.go
- cmd/test2json2gha/main.go
- cmd/test2json2gha/markdown.go
- go.mod
- go.sum
- load_test.go
- test/azlinux_test.go
- test/fixtures/phony.go
- test/fs_test.go
- test/handlers_test.go
- test/signing_test.go
- test/source_test.go
- test/testenv/build.go
- test/testenv/buildkit.go
- test/testenv/buildx.go
- test/var_passthrough_test.go
- test/windows_test.go
- tests.go
- Add some missing `t.Parallal()` and `startTestSpan` calls
- Fix test log output to print line by line instead of per read
- Use the same cache keys for the main Dockerfile and the test fixtures
- Add test stats to GHA summary
- Get tracing reports from integration tests
- Remove GH cache since this wasn't really giving us anything, and maybe was even slowing things down
- ci: Fix issue reporting failures from test panic
- ci: Split integration tests per distro into separate jobs
Supersedes #482 
Fixes #476
> Various improvements to testing

- docs/spec.schema.json
- frontend/azlinux/handle_container.go
- frontend/azlinux/handle_depsonly.go
- frontend/azlinux/handle_rpm.go
- frontend/build.go
- frontend/deb/distro/container.go
- frontend/deb/distro/distro.go
- frontend/deb/distro/pkg.go
- frontend/gateway.go
- frontend/windows/dockerui.go
- frontend/windows/handle_container.go
- image.go
- imgconfig.go
- load.go
- load_test.go
- target.go
- test/windows_test.go
- website/docs/image.md
- website/docs/spec.md
Allows windowscross to produce a single multiplatform image using the specified base images.
Supersedes #480 
Closes #480
> Add support for specifying multiple base images to use in the spec

- docker-bake.hcl
- frontend/mux.go
This allows the error to actually propagate back to the client instead of the ominous "exit code 2" and having to search through the daemon logs to see what happened.
Closes #181
Closes #505
> Add recover for panics from handlers

- docs/spec.schema.json
- tests.go
- website/docs/testing.md
**What this PR does / why we need it**: Changes the typing of `matches` such that it now takes a slice of strings, allowing for easier writing of regex matches for different cases.
Fixes #513 
> Make matches a slice of regexes instead of a single regex

- website/docs/dependencies.md
- website/docs/spec.md
- website/sidebars.ts
**What this PR does / why we need it**: Adds missing documentation for the `PackageDependencies` struct and updates relevant docs with links to it
Fixes #470 
> Add documentation for PackageDependencies

- artifacts.go
- docs/spec.schema.json
- frontend/deb/debroot.go
- frontend/deb/template_custom_dh_installsystemd_postinst.go
- frontend/deb/template_rules.go
- frontend/rpm/template.go
- frontend/windows/handle_zip.go
- helpers.go
- target.go
- test/azlinux_test.go
- test/multiple_artifacts_test.go
- website/docs/artifacts.md
- website/docs/targets.md
This PR allows for target-defined artifacts which is especially useful for windows builds.
Fixes #474
> Allow for target-defined artifacts

- artifacts.go
- docs/spec.schema.json
- frontend/deb/debroot.go
- frontend/rpm/template.go
- frontend/rpm/template_test.go
- test/azlinux_test.go
- website/docs/artifacts.md
For now this is just the most simple config.
We can expand to other options (e.g. shell, home dir) as needed.
Closes #444
> Add support for adding users and groups in spec

- frontend/mux.go
- frontend/windows/handle_zip.go
- load.go
- load_test.go
- test/azlinux_test.go
- test/windows_test.go
- website/docs/spec.md
This sets the name of the target, e.g. `mariner2`, as a build-arg which can be consumed anywhere build-args are accepted in the spec.
This is neccessary in particular for mixed windows/linux builds where something like `GOOS` may neeed to be set (as an example).
> Add DALEC_TARGET built-in arg

- helpers.go
- helpers_test.go
- test/azlinux_test.go
This applies an inheritance type relationship between package dependencies for individual dalec targets and package dependencies specified in the default spec `dependencies` block. Basically, if a dependency field is specified for a particular target, it will be used, otherwise the field from the global dependencies will be inherited. Fields themselves are not merged together; this is an "override if unset in specific target" type of behavior.
Fixes #
> Merge Dependency Fields from Global Spec Dependencies into Targets

- load.go
- load_test.go
- spec.go
This makes it easier to determine if the error is due to the specified field not existing or some other reason.
It also fixes a potential panic there were no extensions set.
> Improve ergonomics for extension fields

- artifacts.go
- docs/spec.schema.json
This should be `libs`, not `libraries`, to match the yaml definition.
> spec: fix "libs" json definition

- packaging/linux/deb/debroot.go
- test/azlinux_test.go
Historically, conffiles is used to help dpkg track configuration files so that user modifications don't get overwritten on upgrades.
Since debhelper v9 this is not needed for anything that goes into /etc as dpkg automatically tracks things under that path. Since we only put conf files into /etc we really don't need conffiles.
This resolves an issue where a spec lists a directory of configs in `artifacts.configFiles` instead of each individual config. With conffiles we end up listing the directory in there which will cause dpkg to error out on install.
> deb: Do not create conffiles

- frontend/debug/handle_sources.go
- frontend/debug/handler.go
- source_test.go
- test/source_test.go
**What this PR does / why we need it**: We need to test to ensure we fail when a patch is either malformed or conflicts with another patch.
Fixes #500 
> Add tests cases for malformed and conflicting patches

- packaging/linux/deb/debroot.go
- packaging/linux/deb/pkg.go
- test/azlinux_test.go
When a patch is in a subdir, the wrong path was used to extract the
patch from the source from.
Additionally, the call to `mountSources` was causing issues afer this
fix.
`mountSources` is just in this case is an optimization so to prevent
dpkg-source from having to re-extract data we already have available.
Since this is causing an issue I decided to just remove it for now.
I believe the two changes included in this PR are playing off each other (ie, one change requires a change in the other).
We'll need to look into this before including this optimization again.
> deb: Fix patches when patch is in subdir

- .github/workflows/ci.yml
- cmd/lint/main.go
- go.mod
- go.sum
- linters/yaml_json_tags.go
- linters/yaml_json_tags_test.go
Example (this is from a commit I added temporarily: https://github.com/Azure/dalec/commit/5bc521734d090c919ea902137dd332fbfd35b091).
> Struct tag linter

- artifacts.go
- docs/spec.schema.json
- packaging/linux/deb/template_rules.go
- packaging/linux/deb/template_rules_test.go
- packaging/linux/deb/templates/debian_rules.tmpl
- packaging/linux/rpm/template.go
- packaging/linux/rpm/template_test.go
- targets/linux/rpm/almalinux/common.go
- test/linux_target_test.go
- test/target_almalinux_test.go
- test/target_rockylinux_test.go
- website/docs/artifacts.md
This is required for some builds, namely building go. On debian targets there is a pretty easy work-around (without this change), but for rpm there is not.
> Add option to disable strip on binaries

- frontend/build.go
- targets/windows/handler.go
- test/windows_test.go
Makes it so when no `--platform` is provided that the default platform
is set to `windows/<arch>` instead of taking the build machine's spec.
> windows: set default targetos to "windows"

- targets/windows/handle_zip.go
- test/windows_test.go
Passes platform and spec to the function that builds the zip from the LLB.  This is needed to build a more proper filename like:
```
<name>_<ver>-<rev>_<arch>.zip
```
Fixes #
> Pass spec and platform to use for building zip file name

- targets/linux/deb/distro/pkg.go
- test/target_ubuntu_test.go
This helps make sure the signer doesn't need to have a ton of logic to know *what* to sign.
> deb: Only send .deb files to be signed

- targets/linux/deb/distro/container.go
- targets/linux/distro_handler.go
- targets/linux/rpm/azlinux/azlinux3.go
- targets/linux/rpm/azlinux/mariner2.go
- targets/linux/rpm/distro/container.go
- test/target_azlinux_test.go
This now uses a virtual package to install base dependencies. In doing so the base dependcies can now be more expressive.
This is needed by azlinux/mariner so that packages can depend on `ca-certificates` without causing a conflict with the base package `prebuilt-ca-certificates`
> rpm: fix issue when installing base deps conflicts with package deps

- packaging/linux/rpm/template.go
- targets/linux/rpm/almalinux/common.go
- targets/linux/rpm/almalinux/v8.go
- targets/linux/rpm/almalinux/v9.go
- targets/linux/rpm/azlinux/azlinux3.go
- targets/linux/rpm/azlinux/common.go
- targets/linux/rpm/azlinux/mariner2.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/distro.go
- targets/linux/rpm/rockylinux/common.go
- targets/linux/rpm/rockylinux/v8.go
- targets/linux/rpm/rockylinux/v9.go
- test/target_azlinux_test.go
As it turns out, the previous "fix" was causing dnf to *always* choose `ca-certificates`, presumably because it is what it sees first in the package repo.
By using a weak dependency we can allow the built package to depend on ca-certificates and ignore the prebuilt-ca-certificates but by default install the prebuilt ones.
The end result of the previous case is we end up with bash and some other tools int he final image, which is undesirable.
ref: https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/
> azlinux: use weak dependency for prebuilt-ca-certificates

- frontend/test_runner.go
- test/linux_target_test.go
Basically it looks like only the last step in a test case was ever being run due incorrectly setting variables in the loop.
> Fix case where multiple test steps are not being run

- .github/workflows/ci.yml
- frontend/build.go
- frontend/debug/handle_gomod.go
- frontend/debug/handle_sources.go
- frontend/gateway.go
- frontend/mux.go
- frontend/test_runner.go
- helpers.go
- source.go
- source_build.go
- source_test.go
- targets/linux/deb/distro/pkg.go
- targets/linux/deb/distro/worker.go
- targets/linux/distro_handler.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/debug.go
- targets/linux/rpm/distro/dnf_install.go
- targets/linux/rpm/distro/pkg.go
- targets/linux/rpm/distro/worker.go
- targets/windows/handle_container.go
- targets/windows/handle_zip.go
- targets/windows/handler.go
- test/linux_target_test.go
- test/target_almalinux_test.go
- test/target_azlinux_test.go
- test/target_rockylinux_test.go
- test/target_ubuntu_test.go
This makes sure that the requested target platform is propagated everywhere it needs to be.
There are some room for improvements here.
For example, source packages really should not
depend on the target platform and we could get
away with using the native platform there.
These kinds of improvements will require some
code restructuring which is out of scope for this
change.
> Properly pass through target platform

- targets/linux/deb/distro/container.go
- targets/linux/deb/distro/install.go
This makes sure the container is fully up to
date in case the container image is stale.
> deb: Upgrade before install container packages

- .github/workflows/ci.yml
- .github/workflows/retag.yml
- .github/workflows/retag/images.yml
This should help prevent CI failures due to DockerHub rate limits.
But after this is merged will require a follow-up to change these refs over.
> Add workflow to retag images used in CI

- .github/workflows/ci.yml
- cmd/test2json2gha/event.go
- cmd/test2json2gha/event_test.go
- cmd/test2json2gha/github.go
- cmd/test2json2gha/github_test.go
- cmd/test2json2gha/main.go
- cmd/test2json2gha/main_test.go
- cmd/test2json2gha/markdown.go
- cmd/test2json2gha/summary.go
- cmd/test2json2gha/summary_test.go
- test/network_test.go
- test/target_azlinux_test.go
Fixes a few issues with the test output parsing in CI:
1. Do not output successful tests to the console. This makes the console basically impossible to render because its too much data.
2. Upload all test logs as artifacts to the CI system (as a replacement to 1).
3. Fix handling of new-lines on errors... mainly we were converting newlines to HTML escaped ones for annotations, but this messed up the console view and made it illegible.
4. Move error annotations to a completely separate output
5. Do not output build logs to the error annotations as this overflows the max annotation size and hides the error. Instead only show logs directly generated from test files.
6. Add option to stream the test output to the console as it is received.
7. Basically rewrites most of it to make things …
> Fix test output format

- packaging/linux/deb/template_control.go
- packaging/linux/deb/template_control_test.go
- packaging/linux/rpm/template.go
- packaging/linux/rpm/template_test.go
- test/linux_target_test.go
- test/target_almalinux_test.go
- test/target_azlinux_test.go
- test/target_rockylinux_test.go
- test/target_ubuntu_test.go
- test/windows_test.go
This makes it so you don't need to specify a difference set of constraints for deb/rpm packages.  Especially important because fields like `replaces` and `conflicts` are not currently distro specific (though I'm realizing now they probably need to be).
> Automatically convert version constraint differences for deb/rpm

- .github/actions/format-repo/action.yml
- .github/actions/setup-source-policy/action.yml
- .github/actions/setup-source-policy/policy.json
- .github/workflows/ci.yml
- test/testenv/buildx.go
This allows us to inject images from the ghcr mirror instead of hitting dockerhub.
> ci: Use buildkit source policy

- docs/spec.schema.json
- packaging/linux/deb/template_changelog.go
- spec.go
- spec_test.go
This is mostly so that when marshaling the
changelog, the date is formatted in a way that we
are expecting and not a full RFC 3339 date-time.
> Add custom marshalling for changelog date

- cache.go
- docs/spec.schema.json
- helpers.go
- load_test.go
- test/cache_test.go
- test/linux_target_test.go
- test/target_almalinux_test.go
- test/target_debian_test.go
- test/target_rockylinux_test.go
- test/target_ubuntu_test.go
- website/docs/caches.md
This allows bazel users to keep a cache of bazel artifacts that
persists between builds and can even be shared between different
projects.
One slight difference here is we are not automatically injecting a bazel
cache at any point, it must always be manually added.
We may change this in the future but as I understand it, it will
actually be difficult to detect bazel anyway in most builds due to bazel
either not being available in the package manager or the *right* version
of bazel not being available.
> Add support for bazel caches similar to the gobuild cache.

- docs/spec.schema.json
- helpers.go
- load.go
- packaging/linux/deb/template_control.go
- packaging/linux/deb/template_control_test.go
- packaging/linux/rpm/template.go
- packaging/linux/rpm/template_test.go
- target.go
- website/docs/spec.md
- website/docs/targets.md
Packages in different targets may have different names or possibly versions. This allows the user to specify a target-specific provides/conflicts/replaces.
> Allow target-specific provides/conflicts/replaces

- artifacts.go
- docs/spec.schema.json
- packaging/linux/deb/template_control.go
- packaging/linux/deb/template_rules_test.go
- packaging/linux/rpm/template.go
- packaging/linux/rpm/template_test.go
- test/linux_target_test.go
- website/docs/artifacts.md
This commit adds a new configuration option to the `artifacts` section `disable_automatic_requires` which, when set to true, disables the automatic injection of runtime dependencies into the generated packages.
> Add support for disabling automatic runtime dependency injection

- packaging/linux/deb/template_control.go
- packaging/linux/deb/template_control_test.go
- packaging/linux/rpm/template.go
- packaging/linux/rpm/template_test.go
This was looking at just the top-level artifacts instead of checking if the target-specific artifacts had a disable_auto_requires field.
> Make sure rpm/deb use disable_auto_requires from target-specific artifacts when available

- website/docs/intro.md
The targets listed in the README had an addition from https://github.com/Azure/dalec/pull/468 that wasn't yet reflected in the website docs. This change updates the docs to match the current status as described in the README.
> Updating docs to match targets in README

- .github/workflows/ci.yml
- .github/workflows/retag.yml
- .github/workflows/retag/images.yml
- cmd/retagger/main.go
- go.mod
- go.sum
Also added a custom retag CLI due to a [bug in docker](https://github.com/Azure/dalec/pull/646#issuecomment-2920725771).
retag CLI is quite a bit more efficient anyway since it doesn't need to unpack tar.gz files and just basically treats the whole source registry as a containerd [content.Provider](https://godoc.org/github.com/containerd/containerd/v2/core/content#Provider)
> Add msft-go to the list of mirror images.

- cmd/retagger/main.go
We are getting 429 and 502 errors from GHCR.
Hopefully limiting the concurrency will help...
> retagger: limit push concurrency

- .github/workflows/ci.yml
This just makes it so there is less noise in the main console log
> ci: Dump buildkit logs to artifacts instead of main console log

- docs/spec.schema.json
- source.go
- spec.go
- test/source_test.go
- website/docs/sources.md
The docker image source currently allows you to mount other sources in for *all* commands.
This change allows you to specify a mount for a specific command.
This can help improve performance by only mounting the sources that are needed for a specific command by improving the cache hit rate.
Closes #437
> Add support for mounting sources per command

- artifacts.go
This doesn't change what package managers will do with the licenses (ie omit them from the install process) but it does make sure that we don't consider a license file as a doc which would make it so all packages have a doc (or at least all packages we build).
Addresses https://github.com/Azure/dalec/pull/692/files/7b54d4a9d9396104f749ab03b36c92caf1e43e0e#diff-5980dac7473b3afee451e0b927cf5c7449e94ff4e034d8f46888338886c9c146
> Don't consider licenses as doc files.

- .github/workflows/ci.yml
This is just a waste of resources since the dependabot config is not checked by the ci workflow.
> ci: Don't run workflow for changes to dependabot workflow

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/retag.yml
- .github/workflows/worker-images.yml
This mostly just wants to make sure that read permissions are set the root and write permissions just on the job that needs it.
> ci: Set GITHUB_TOKEN perms where recommended

- cache.go
- targets/linux/deb/debian/bullseye.go
This was never really neccessary and only added to make sure tests can run effectively.
It did not help tests at all and also makes it so we can end up always busting the buildkit cache for builds with a bazel cache.
> bazel: Remove unnecessary llb.IgnoreCache

- SECURITY.md
Microsoft is standardizing the SECURITY.md file; this copies in the text from https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md?plain=1 which is what new repos are generated with as of July 16th, 2025.
Note that the content on https://aka.ms/SECURITY.md is largely the same as what this file previously contained.
> Update SECURITY.md to point at aka.ms/SECURITY.md

- targets/linux/rpm/almalinux/v8.go
- targets/linux/rpm/almalinux/v9.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/distro.go
- targets/linux/rpm/distro/dnf_install.go
- test/createrepo.go
- test/custom_repo_test.go
- test/linux_target_test.go
- test/target_azlinux_test.go
- test/target_ubuntu_test.go
- test/windows_test.go
- website/docs/repositories.md
dnf automatically refreshes repo metadata after a configured expiry period.
This change removes our manual metadata refreshes (which we end up doing twice per package install command).
This had some extra implications around custom repos in CI.
To work around this I have namespaced all custom repo ID's with a random string in order to prevent caches from mixing.
This also spotted an issue with the cache for almalinux.
Alma does not include the $basearch in the mirrorlist url, which means that when dnf computes a cache key that gets used in /var/cache/dnf it is not unique per arch which broke the cross_platform test for alma.
To fix this I added an option to the rpm distro config to namespace the buildkit cache key for the dnf cache with the target platform.
Addresses part of #742
> dnf: remove manual metadata refresh

- targets/linux/rpm/almalinux/v8.go
- targets/linux/rpm/almalinux/v9.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/distro.go
- targets/linux/rpm/distro/dnf_install.go
- test/createrepo.go
- test/custom_repo_test.go
- test/linux_target_test.go
- test/target_azlinux_test.go
- test/target_ubuntu_test.go
- test/windows_test.go
- website/docs/repositories.md
Since we just ran a `makecache` (which is neccessary or else dependency pinning tests will fail depending on test ordering, which also means real builds would have a problem) we don't need to hit the repo again to refresh the metadata.
(cherry picked from commit 4bbb3d19de74ef6843f79406c4ed40117e28175b)
> [0.16] dnf: remove "--refresh" from install command

- targets/linux/deb/debian/bullseye.go
- targets/linux/rpm/almalinux/v8.go
- targets/linux/rpm/almalinux/v9.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/distro.go
- targets/linux/rpm/distro/dnf_install.go
- test/createrepo.go
- test/custom_repo_test.go
- test/linux_target_test.go
- test/target_azlinux_test.go
- test/target_ubuntu_test.go
- test/windows_test.go
- website/docs/repositories.md
Since we just ran a `makecache` (which is neccessary or else dependency pinning tests will fail depending on test ordering, which also means real builds would have a problem) we don't need to hit the repo again to refresh the metadata.
(cherry picked from commit 4bbb3d19de74ef6843f79406c4ed40117e28175b)
Fixes #
> [0.14] dnf: remove "--refresh" from install command

- source_http.go
- source_test.go
In the sources refactor we neglected to set a source path when mounting http sources, as such they end up getting mounted as directories instead of files.
Fixes #750
> source: http: make sure we set a source path for mounts

- targets/linux/deb/distro/container.go
- targets/linux/rpm/distro/container.go
- targets/linux/rpm/distro/pkg.go
- targets/linux/rpm/distro/worker.go
Makes sure `--no-cache` and `--no-cache-filter` is respected for rpm-based targets.
> rpm: Fix issue where ignore-cache is not respected
