frontend/rpm/template.go

Issue #63
Adds quotes to paths in shells

Add quotes to paths in shells

---

frontend/rpm/template.go

This PR covers at bit more of Issue #63 of improving quoting for path strings.

add quotes for value on export command.

---

load.go
source.go
source_test.go
spec.go

1. Fix inline dir should be rooted at `/` not `/<sourcename>`
2. Untangle command/test/testspec 
On 2, this was just some incidental duplication.
The code is easier to reason about as separate implementations.

Minor fixes

---

.github/dependabot.yml

group dependabot actions bumps together

ci: group dependabot actions

---

README.md
docs/editor-support.md

Fix a typo, and add more examples on enabling json schema on vscode
Fixes #

Updating docs

---

frontend/mariner2/handle_container.go
frontend/mariner2/handle_depsonly.go
frontend/mariner2/handle_rpm.go

fix tdnf typo

---

website/docusaurus.config.ts

Fix baseurl for docs site

---

frontend/azlinux/handle_container.go
frontend/azlinux/handle_depsonly.go
frontend/azlinux/handle_rpm.go
frontend/azlinux/install.go
frontend/debug/handle_sources.go
frontend/rpm/handle_sources.go
frontend/rpm/rpmbuild.go
frontend/windows/handle_container.go
frontend/windows/handle_zip.go
generator_gomod.go
helpers.go
source.go
source_build_test.go
source_test.go
test/azlinux_test.go
test/fs_test.go
test/handlers_test.go
test/helpers_test.go
test/main_test.go
test/signing_test.go
test/source_test.go
test/testenv/buildx.go
test/testenv/builld.go
test/var_passthrough_test.go
test/windows_test.go

This is a bunch of refactoring I've pulled out of my jammy PR which will help to get in so that there aren't so many conflicts from upcoming changes.

Refactor a bunch of things

---

test/windows_test.go

PR #320 was incomplete because it did not include this test.
Applies to #282, but another PR is needed to fully resolve it

fix: Add signing-skipping test for Windows

---

test/azlinux_test.go

Fix data race on `spec` in pinned build dependencies test

---

website/docusaurus.config.ts

docs: add search

---

frontend/azlinux/handle_container.go
frontend/azlinux/handle_depsonly.go
frontend/azlinux/handle_rpm.go
frontend/jammy/handle_container.go
frontend/jammy/handle_deb.go
test/azlinux_test.go

Before this the package tests were only run when building a container and not when just building a package.

Run package spec tests for packaging targets

---

.github/workflows/ci.yml
test/main_test.go

fix typo and redundant import (maybe?)
Fixes #

fix typo and redundant import

---

frontend/azlinux/azlinux3.go
frontend/azlinux/mariner2.go

This includes root CA's, tzdata, and basic filesystem stuff.

Use distroless-packges-minimal as the base package

---

website/docs/sources.md

add multi-module gomod support docs

---

website/docs/quickstart.md

This resolves a small typo in the docs. 
Fixes #

Fix docs typo

---

.github/workflows/ci.yml

Fixes: https://github.com/Azure/dalec/issues/68
Fixes #

ci: build example in docs during ci

---

frontend/mux.go

Reading through the code and noticed what looks to be an incorrect comment regarding the purpose of Add, which seems to be adding a targetPath and not a targetKey.
Fixes #

Fix typo in comment

---

cmd/test2json2gha/main.go

Test logs can be quite large and overflow the max summary size.
Instead just log the test name in the summary (this is for slow tests).

tests: Do not write test logs to summary

---

load.go
load_test.go
target.go

Allow build args in target image config

---

website/docs/container-only-builds.md

fix sample in container-only-builds.md
Fixes #

fix sample in container-only-builds.md

---

website/docs/image.md

Update bases doc for windows

---

.github/workflows/ci.yml

Add release branches to CI.

---

docker-bake.hcl
packaging/linux/deb/debroot.go
packaging/linux/deb/pkg.go
packaging/linux/deb/templates/debian_rules.tmpl
targets/linux/deb/distro/install.go

Deb and multi-sources structure

---

website/docs/sources.md

Markdown internal links must be lowercase.
Fixes #

Fix broken internal link

---

website/docs/spec.md

Add docs for the changelog format

---

load.go
load_test.go
source.go

Add support for arg expansion in patches, sources include/exclude/path

---

generator_gomod.go

This keeps a shared persistent go module cache across all builds. We still extract just the modules we need for the individual build but but now we can re-use already fetched modules just like one would expect from a go module cache.
Unfortunately there is no good way to automate testing this reliably due to buildkit caching.
After #621 is in, we can address this potentially by adding an ignore context for the gomod fetching so that a test will run that piece of code regardless of buildkit caching.

Add persistent go module cache

---

.github/actions/setup-source-policy/policy.json
.github/workflows/frontend-image.yml
.github/workflows/retag.yml
.github/workflows/retag/images.yml
targets/linux/rpm/azlinux/azlinux3.go

More image mirroring because MCR has is causing too many issues with CI.

Retag all external images

---

test/testenv/buildx.go

- Use feature check instead of version check for buildx dial-stdio
- Fix subprocess handling for buildx dial-stdio

Fix buildx version check

---

.github/workflows/ci.yml

bump ci timeout up 10 minutes to discover issue

---

docs/spec.schema.json
generator_nodemodules.go
helpers.go
load.go
load_test.go
packaging/linux/deb/debroot.go
packaging/linux/deb/pkg.go
packaging/linux/rpm/sources.go
packaging/linux/rpm/template.go
packaging/linux/rpm/template_test.go
spec.go
targets/linux/rpm/distro/debug.go
targets/windows/handle_zip.go
test/linux_target_test.go
test/source_test.go
test/windows_test.go
website/docs/sources.md

poc for node_modules caching via npm.
previously including yarn, however getting yarn into build stage is not straight forward 
Fixes #

node_modules caching via npm

---

docs/spec.schema.json
spec.go
website/docs/sources.md

- Correct syntax of generate in docs 
- Change Spec Schema, to not required every key in generate entry instead to one of
Fixes #643

update spec schema + docs

---

.github/workflows/worker-images.yml

release: fix tag reference in worker images

---

README.md
website/docs/intro.md

docs: update readme and intro

---

load.go
load_test.go

Turns out this actually found a bug!
Not a security issue or anything just a normal bug.

Add fuzz test
